"""Initial migration

Revision ID: 3224b1405d17
Revises: 
Create Date: 2025-11-02 14:00:04.206309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3224b1405d17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customs_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shipping_fee', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('insurance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('books_locked_until', sa.DateTime(), nullable=True),
    sa.Column('accounting_method', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_number', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('origin_port', sa.String(length=200), nullable=True),
    sa.Column('destination_port', sa.String(length=200), nullable=True),
    sa.Column('departure_date', sa.DateTime(), nullable=True),
    sa.Column('arrival_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('cost_freight_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_insurance_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('shipping_company', sa.String(length=200), nullable=True),
    sa.Column('container_number', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_number')
    )
    op.create_table('shipping_region_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('region_name', sa.String(length=200), nullable=True),
    sa.Column('price_omr', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=True),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_code', 'category', name='uq_shipping_region_code_category')
    )
    with op.batch_alter_table('shipping_region_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_region_prices_region_code'), ['region_code'], unique=False)

    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills_of_lading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bol_number', sa.String(length=100), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bol_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('price_category', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('buyer_number', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_account_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('deposit_account_code', sa.String(length=20), nullable=False),
    sa.Column('auction_account_code', sa.String(length=20), nullable=True),
    sa.Column('service_revenue_account_code', sa.String(length=20), nullable=False),
    sa.Column('logistics_expense_account_code', sa.String(length=20), nullable=False),
    sa.Column('receivable_account_code', sa.String(length=20), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_account_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_account_structures_customer_id'), ['customer_id'], unique=True)

    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('auction_date', sa.DateTime(), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('auction_url', sa.Text(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=30), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('owner_customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_location', sa.String(length=200), nullable=True),
    sa.Column('container_number', sa.String(length=100), nullable=True),
    sa.Column('booking_number', sa.String(length=100), nullable=True),
    sa.Column('purchase_price_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['owner_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_share_token'), ['share_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_vehicles_vin'), ['vin'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('cost_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('amount_omr', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_deposits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_deposits_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_deposits_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_deposits_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('international_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('freight_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('insurance_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('auction_fees_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('customs_omr', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('vat_omr', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('local_transport_omr', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('misc_omr', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('invoice_type', sa.String(length=20), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('total_omr', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('exchange_rate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['exchange_rate_id'], ['exchange_rates.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('operational_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('original_currency', sa.String(length=3), nullable=True),
    sa.Column('amount_omr', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('exchange_rate_id', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['exchange_rate_id'], ['exchange_rates.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operational_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_expenses_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_expenses_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('vehicle_account_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('deposit_account_code', sa.String(length=20), nullable=False),
    sa.Column('auction_account_code', sa.String(length=20), nullable=False),
    sa.Column('freight_account_code', sa.String(length=20), nullable=False),
    sa.Column('customs_account_code', sa.String(length=20), nullable=False),
    sa.Column('commission_account_code', sa.String(length=20), nullable=False),
    sa.Column('storage_account_code', sa.String(length=20), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_account_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_account_structures_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_account_structures_vehicle_id'), ['vehicle_id'], unique=True)

    op.create_table('vehicle_sale_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('asking_price_omr', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('note_admin', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_sale_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_sale_listings_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_sale_listings_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('vehicle_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount_omr', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('auction_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('is_client_fund', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('amount_omr', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('credit', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_lines_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_lines_entry_id'), ['entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_lines_entry_id'))
        batch_op.drop_index(batch_op.f('ix_journal_lines_account_id'))

    op.drop_table('journal_lines')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_id'))

    op.drop_table('payments')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_date'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_customer_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_auction_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))

    op.drop_table('invoice_items')
    op.drop_table('vehicle_shipments')
    with op.batch_alter_table('vehicle_sale_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_sale_listings_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_sale_listings_customer_id'))

    op.drop_table('vehicle_sale_listings')
    with op.batch_alter_table('vehicle_account_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_account_structures_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_account_structures_client_id'))

    op.drop_table('vehicle_account_structures')
    with op.batch_alter_table('operational_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_expenses_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_operational_expenses_auction_id'))

    op.drop_table('operational_expenses')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_vehicle_id'))

    op.drop_table('invoices')
    op.drop_table('international_costs')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_documents_shipment_id'))

    op.drop_table('documents')
    with op.batch_alter_table('customer_deposits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_deposits_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_customer_deposits_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_deposits_auction_id'))

    op.drop_table('customer_deposits')
    op.drop_table('cost_items')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_code'))
        batch_op.drop_index(batch_op.f('ix_accounts_client_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vin'))
        batch_op.drop_index(batch_op.f('ix_vehicles_share_token'))

    op.drop_table('vehicles')
    op.drop_table('auctions')
    with op.batch_alter_table('client_account_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_account_structures_customer_id'))

    op.drop_table('client_account_structures')
    op.drop_table('buyers')
    op.drop_table('customers')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('bills_of_lading')
    op.drop_table('testimonials')
    with op.batch_alter_table('shipping_region_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_region_prices_region_code'))

    op.drop_table('shipping_region_prices')
    op.drop_table('shipments')
    op.drop_table('settings')
    op.drop_table('roles')
    op.drop_table('notifications')
    op.drop_table('exchange_rates')
    op.drop_table('backups')
    # ### end Alembic commands ###
